"use client";
import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Lang = "fr" | "ar" | "en";

const translations = {
  fr: {
    nav: {
      services: "Services",
      howItWorks: "Comment ça marche",
      becomeProvider: "Devenir prestataire",
      login: "Connexion",
      register: "S'inscrire",
      logout: "Déconnexion",
      menu: {
        profile: "Mon profil",
        messages: "Messages",
        notifications: "Notifications",
        location: "Ma localisation",
        settings: "Paramètres",
        logout: "Déconnexion",
      },
    },
    auth: {
      login: {
        title: "Connexion",
        subtitle: "Content de vous revoir 👋",
        username: "Nom d'utilisateur",
        usernamePlaceholder: "votre_pseudo",
        password: "Mot de passe",
        passwordPlaceholder: "••••••••",
        submit: "Se connecter",
        loading: "Connexion...",
        noAccount: "Pas encore de compte ?",
        signUp: "S'inscrire",
      },
      register: {
        title: "Créer un compte",
        subtitle: "Rejoignez la communauté JariApp 🇩🇿",
        seekingLabel: "🔍 Je cherche",
        providingLabel: "🔧 Je propose",
        firstName: "Prénom",
        lastName: "Nom",
        username: "Nom d'utilisateur",
        usernamePlaceholder: "votre_pseudo",
        usernameHint: "Lettres, chiffres et _ uniquement",
        phone: "Téléphone",
        phoneOptional: "(optionnel)",
        phonePlaceholder: "0555 123 456",
        wilaya: "Wilaya",
        wilayaPlaceholder: "Sélectionner votre wilaya",
        password: "Mot de passe",
        passwordPlaceholder: "Minimum 6 caractères",
        submit: "Créer mon compte",
        loading: "Inscription...",
        hasAccount: "Déjà un compte ?",
        signIn: "Se connecter",
      },
    },
    hero: {
      badge: "🇩🇿 Disponible dans toute l'Algérie",
      line1: "Trouvez des prestataires",
      highlight: "de confiance",
      line2: "près de chez vous",
      sub: "Plomberie, électricité, ménage, cours particuliers… Réservez un professionnel vérifié dans votre quartier en quelques minutes.",
      cta1: "Trouver un prestataire",
      cta2: "Comment ça marche",
      loginHint: "Déjà inscrit ?",
      loginLink: "Se connecter",
    },
    stats: {
      providers: "prestataires actifs",
      cities: "wilayas couvertes",
      rating: "note moyenne",
    },
    trust: {
      title: "Pourquoi choisir JariApp ?",
      verified: { title: "Profils vérifiés", desc: "Chaque prestataire est contrôlé avant d'apparaître sur la plateforme." },
      fast: { title: "Réponse rapide", desc: "Recevez des réponses de professionnels qualifiés en moins de 2h." },
      free: { title: "Gratuit pour les clients", desc: "Aucun frais d'inscription ni commission cachée." },
    },
    services: {
      title: "Explorez nos catégories",
      sub: "Des centaines de professionnels qualifiés dans toute l'Algérie",
      items: [
        "Plomberie", "Électricité", "Climatisation", "Mécanique",
        "Ménage", "Cours particuliers", "Peintre & Plâtrier", "Chauffeur",
        "Maçonnerie", "Informatique", "Déménagement", "Électroménager",
      ],
    },
    how: {
      title: "Comment ça marche ?",
      sub: "Trouvez et réservez un service en 3 étapes simples",
      steps: [
        { title: "Décrivez votre besoin", desc: "Choisissez la catégorie et décrivez votre besoin en quelques mots." },
        { title: "Choisissez un prestataire", desc: "Parcourez les profils vérifiés près de vous avec avis et tarifs." },
        { title: "Réservez & profitez", desc: "Confirmez la réservation, le prestataire se déplace chez vous." },
      ],
    },
    testimonials: {
      title: "Ils font confiance à JariApp",
      items: [
        { name: "Karim B.", city: "Alger", role: "Client", text: "J'ai trouvé un excellent plombier en 20 minutes. Rapide, propre et très professionnel !" },
        { name: "Amina L.", city: "Oran", role: "Cliente", text: "Les prestataires sont sérieux et ponctuels. Je recommande JariApp à tous mes voisins." },
        { name: "Mohamed A.", city: "Constantine", role: "Prestataire", text: "Depuis JariApp, j'ai triplé mon nombre de clients. Une plateforme vraiment excellente !" },
      ],
    },
    provider: {
      title: "Vous êtes prestataire ?",
      sub: "Rejoignez notre réseau, développez votre clientèle et gérez vos réservations facilement. Inscription 100% gratuite.",
      cta: "Rejoindre JariApp →",
    },
    footer: {
      tagline: "Services entre voisins en Algérie",
      links: ["Confidentialité", "CGU", "Contact"],
      rights: "© 2025 JariApp. Tous droits réservés.",
    },
    feed: {
      greeting: "Bonjour",
      subtitle: "Que cherchez-vous aujourd'hui ?",
      publishBtn: "Publier une annonce",
      publishSubtitle: "Service · Vente · Location · Demande · Emploi",
      publishTitle: "Que voulez-vous publier ?",
      myAnnonces: "Mes annonces actives",
      seeAll: "Voir tout →",
      newAnnonce: "Nouvelle annonce",
      active: "Actif",
      recentAnnonces: "Annonces récentes",
      filters: { all: "Tout", marche: "Marché", services: "Services", emploi: "Emploi" },
      types: { service: "Service", vente: "Vente", demande: "Demande", emploi: "Emploi", location: "Location", recrute: "Recrute", candidate: "Candidate" },
      publish: { service: "Proposer un service", vente: "Vendre un objet", demande: "Publier une demande", emploi: "Offre / Recherche emploi", location: "Location" },
      modal: {
        title: "Publier une annonce de service",
        modeProposer: "🔧 Proposer",
        modeDemander: "🔍 Demander",
        categoryLabel: "Catégorie",
        categoryPlaceholder: "Rechercher une catégorie...",
        categoryNotFound: "Aucune catégorie trouvée",
        titreProposer: "Intitulé du service",
        titreDemander: "Ce que vous cherchez",
        placeholderTitreProposer: "Ex : Plombier disponible à Alger",
        placeholderTitreDemander: "Ex : Cherche électricien pour fuite",
        descLabel: "Description",
        placeholderDescProposer: "Décrivez votre service, zones d'intervention, expérience...",
        placeholderDescDemander: "Décrivez votre besoin en détail...",
        wilayaLabel: "Wilaya",
        wilayaPlaceholder: "Sélectionner votre wilaya",
        dateLabel: "Date souhaitée",
        dateFlexible: "Date flexible / à discuter",
        submitProposer: "Publier mon service",
        submitDemander: "Publier ma demande",
        publishing: "Publication...",
        successTitle: "Annonce publiée !",
        successSub: "Elle apparaît maintenant dans le feed.",
        charMin: "min",
      },
    },
  },

  ar: {
    nav: {
      services: "الخدمات",
      howItWorks: "كيف يعمل",
      becomeProvider: "كن مزود خدمة",
      login: "تسجيل الدخول",
      register: "إنشاء حساب",
      logout: "تسجيل الخروج",
      menu: {
        profile: "ملفي الشخصي",
        messages: "الرسائل",
        notifications: "الإشعارات",
        location: "موقعي",
        settings: "الإعدادات",
        logout: "تسجيل الخروج",
      },
    },
    auth: {
      login: {
        title: "تسجيل الدخول",
        subtitle: "مرحباً بعودتك 👋",
        username: "اسم المستخدم",
        usernamePlaceholder: "اسم_المستخدم",
        password: "كلمة المرور",
        passwordPlaceholder: "••••••••",
        submit: "تسجيل الدخول",
        loading: "جارٍ الدخول...",
        noAccount: "ليس لديك حساب؟",
        signUp: "إنشاء حساب",
      },
      register: {
        title: "إنشاء حساب",
        subtitle: "انضم إلى مجتمع JariApp 🇩🇿",
        seekingLabel: "🔍 أبحث عن خدمة",
        providingLabel: "🔧 أقدم خدمة",
        firstName: "الاسم الأول",
        lastName: "اللقب",
        username: "اسم المستخدم",
        usernamePlaceholder: "اسم_المستخدم",
        usernameHint: "حروف وأرقام و _ فقط",
        phone: "الهاتف",
        phoneOptional: "(اختياري)",
        phonePlaceholder: "0555 123 456",
        wilaya: "الولاية",
        wilayaPlaceholder: "اختر ولايتك",
        password: "كلمة المرور",
        passwordPlaceholder: "6 أحرف على الأقل",
        submit: "إنشاء الحساب",
        loading: "جارٍ التسجيل...",
        hasAccount: "لديك حساب؟",
        signIn: "تسجيل الدخول",
      },
    },
    hero: {
      badge: "🇩🇿 متوفر في جميع أنحاء الجزائر",
      line1: "ابحث عن مزودي خدمات",
      highlight: "موثوقين",
      line2: "بالقرب منك",
      sub: "سباكة، كهرباء، تنظيف، دروس خصوصية… احجز محترفًا موثقًا في حيّك في دقائق.",
      cta1: "ابحث عن مزود خدمة",
      cta2: "كيف يعمل",
      loginHint: "لديك حساب؟",
      loginLink: "تسجيل الدخول",
    },
    stats: {
      providers: "مزود خدمة نشط",
      cities: "ولاية مغطاة",
      rating: "متوسط التقييم",
    },
    trust: {
      title: "لماذا تختار JariApp؟",
      verified: { title: "ملفات موثقة", desc: "كل مزود خدمة يخضع للمراجعة قبل النشر على المنصة." },
      fast: { title: "رد سريع", desc: "احصل على رد من محترفين مؤهلين في أقل من ساعتين." },
      free: { title: "مجاني للعملاء", desc: "لا رسوم تسجيل ولا عمولات مخفية." },
    },
    services: {
      title: "استكشف فئاتنا",
      sub: "مئات المحترفين المؤهلين في جميع أنحاء الجزائر",
      items: [
        "سباكة", "كهرباء", "تكييف", "ميكانيكا",
        "تنظيف", "دروس خاصة", "دهان وبلاستير", "سائق",
        "بناء وتشييد", "إعلام آلي", "نقل عفش", "إصلاح أجهزة",
      ],
    },
    how: {
      title: "كيف يعمل؟",
      sub: "ابحث واحجز خدمة في 3 خطوات بسيطة",
      steps: [
        { title: "صف احتياجك", desc: "اختر الفئة وصف ما تحتاجه في بضع كلمات." },
        { title: "اختر مزود الخدمة", desc: "تصفح الملفات الموثقة بالقرب منك مع التقييمات والأسعار." },
        { title: "احجز واستمتع", desc: "أكد الحجز وسيأتي مزود الخدمة إليك في الوقت المحدد." },
      ],
    },
    testimonials: {
      title: "يثقون في JariApp",
      items: [
        { name: "كريم ب.", city: "الجزائر", role: "عميل", text: "وجدت سباكًا ممتازًا في أقل من 20 دقيقة. سريع ونظيف ومحترف جداً!" },
        { name: "أمينة ل.", city: "وهران", role: "عميلة", text: "مزودو الخدمة جادون وملتزمون بالمواعيد. أنصح به لجميع الجيران!" },
        { name: "محمد أ.", city: "قسنطينة", role: "مزود خدمة", text: "منذ انضمامي إلى JariApp، تضاعف عدد عملائي ثلاث مرات. منصة رائعة!" },
      ],
    },
    provider: {
      title: "هل أنت مزود خدمة؟",
      sub: "انضم إلى شبكتنا، وسّع قاعدة عملائك وأدر حجوزاتك بسهولة. التسجيل مجاني 100%.",
      cta: "← انضم إلى JariApp",
    },
    footer: {
      tagline: "خدمات بين الجيران في الجزائر",
      links: ["الخصوصية", "الشروط", "اتصل بنا"],
      rights: "© 2025 JariApp. جميع الحقوق محفوظة.",
    },
    feed: {
      greeting: "مرحباً",
      subtitle: "ماذا تبحث عنه اليوم؟",
      publishBtn: "نشر إعلان",
      publishSubtitle: "خدمة · بيع · إيجار · طلب · توظيف",
      publishTitle: "ماذا تريد أن تنشر؟",
      myAnnonces: "إعلاناتي النشطة",
      seeAll: "← عرض الكل",
      newAnnonce: "إعلان جديد",
      active: "نشط",
      recentAnnonces: "الإعلانات الأخيرة",
      filters: { all: "الكل", marche: "السوق", services: "الخدمات", emploi: "التوظيف" },
      types: { service: "خدمة", vente: "بيع", demande: "طلب", emploi: "توظيف", location: "إيجار", recrute: "يوظّف", candidate: "مرشح" },
      publish: { service: "تقديم خدمة", vente: "بيع شيء", demande: "نشر طلب", emploi: "عرض / طلب عمل", location: "إيجار" },
      modal: {
        title: "نشر إعلان خدمة",
        modeProposer: "🔧 تقديم خدمة",
        modeDemander: "🔍 طلب خدمة",
        categoryLabel: "الفئة",
        categoryPlaceholder: "ابحث عن فئة...",
        categoryNotFound: "لا توجد فئة مطابقة",
        titreProposer: "عنوان الخدمة",
        titreDemander: "ما تبحث عنه",
        placeholderTitreProposer: "مثال: سباك متاح في الجزائر",
        placeholderTitreDemander: "مثال: أبحث عن كهربائي",
        descLabel: "الوصف",
        placeholderDescProposer: "صف خدمتك، منطقة العمل، خبرتك...",
        placeholderDescDemander: "صف حاجتك بالتفصيل...",
        wilayaLabel: "الولاية",
        wilayaPlaceholder: "اختر ولايتك",
        dateLabel: "التاريخ المطلوب",
        dateFlexible: "التاريخ مرن / للنقاش",
        submitProposer: "نشر خدمتي",
        submitDemander: "نشر طلبي",
        publishing: "جارٍ النشر...",
        successTitle: "تم نشر الإعلان!",
        successSub: "يظهر الآن في الصفحة الرئيسية.",
        charMin: "أدنى",
      },
    },
  },

  en: {
    nav: {
      services: "Services",
      howItWorks: "How it works",
      becomeProvider: "Become a provider",
      login: "Log in",
      register: "Sign up",
      logout: "Log out",
      menu: {
        profile: "My profile",
        messages: "Messages",
        notifications: "Notifications",
        location: "My location",
        settings: "Settings",
        logout: "Log out",
      },
    },
    auth: {
      login: {
        title: "Log in",
        subtitle: "Welcome back 👋",
        username: "Username",
        usernamePlaceholder: "your_username",
        password: "Password",
        passwordPlaceholder: "••••••••",
        submit: "Log in",
        loading: "Logging in...",
        noAccount: "No account yet?",
        signUp: "Sign up",
      },
      register: {
        title: "Create an account",
        subtitle: "Join the JariApp community 🇩🇿",
        seekingLabel: "🔍 I'm looking",
        providingLabel: "🔧 I'm offering",
        firstName: "First name",
        lastName: "Last name",
        username: "Username",
        usernamePlaceholder: "your_username",
        usernameHint: "Letters, numbers and _ only",
        phone: "Phone",
        phoneOptional: "(optional)",
        phonePlaceholder: "0555 123 456",
        wilaya: "Wilaya",
        wilayaPlaceholder: "Select your wilaya",
        password: "Password",
        passwordPlaceholder: "Minimum 6 characters",
        submit: "Create my account",
        loading: "Signing up...",
        hasAccount: "Already have an account?",
        signIn: "Log in",
      },
    },
    hero: {
      badge: "🇩🇿 Available across Algeria",
      line1: "Find trusted",
      highlight: "service providers",
      line2: "near you",
      sub: "Plumbing, electricity, cleaning, tutoring… Book a verified professional in your neighborhood in minutes.",
      cta1: "Find a provider",
      cta2: "How it works",
      loginHint: "Already have an account?",
      loginLink: "Log in",
    },
    stats: {
      providers: "active providers",
      cities: "wilayas covered",
      rating: "average rating",
    },
    trust: {
      title: "Why choose JariApp?",
      verified: { title: "Verified profiles", desc: "Every provider is reviewed before appearing on the platform." },
      fast: { title: "Fast response", desc: "Get responses from qualified professionals in under 2 hours." },
      free: { title: "Free for clients", desc: "No registration fees or hidden commissions." },
    },
    services: {
      title: "Explore our categories",
      sub: "Hundreds of qualified professionals across Algeria",
      items: [
        "Plumbing", "Electricity", "A/C & Heating", "Car Mechanics",
        "Cleaning", "Tutoring", "Painter & Plasterer", "Driver",
        "Masonry", "IT Repair", "Moving", "Appliance Repair",
      ],
    },
    how: {
      title: "How does it work?",
      sub: "Find and book a service in 3 simple steps",
      steps: [
        { title: "Describe your need", desc: "Choose the category and describe what you need in a few words." },
        { title: "Choose a provider", desc: "Browse verified profiles near you with reviews and rates." },
        { title: "Book & enjoy", desc: "Confirm the booking and the provider comes to you." },
      ],
    },
    testimonials: {
      title: "They trust JariApp",
      items: [
        { name: "Karim B.", city: "Algiers", role: "Client", text: "I found an excellent plumber in 20 minutes. Fast, clean and very professional!" },
        { name: "Amina L.", city: "Oran", role: "Client", text: "The providers are serious and punctual. I recommend JariApp to all my neighbors." },
        { name: "Mohamed A.", city: "Constantine", role: "Provider", text: "Since joining JariApp, I've tripled my number of clients. Truly excellent platform!" },
      ],
    },
    provider: {
      title: "Are you a provider?",
      sub: "Join our network, grow your client base and manage your bookings easily. 100% free registration.",
      cta: "Join JariApp →",
    },
    footer: {
      tagline: "Neighbor services in Algeria",
      links: ["Privacy", "Terms", "Contact"],
      rights: "© 2025 JariApp. All rights reserved.",
    },
    feed: {
      greeting: "Hello",
      subtitle: "What are you looking for today?",
      publishBtn: "Post an ad",
      publishSubtitle: "Service · Sale · Rental · Request · Job",
      publishTitle: "What do you want to post?",
      myAnnonces: "My active listings",
      seeAll: "See all →",
      newAnnonce: "New listing",
      active: "Active",
      recentAnnonces: "Recent listings",
      filters: { all: "All", marche: "Market", services: "Services", emploi: "Jobs" },
      types: { service: "Service", vente: "Sale", demande: "Request", emploi: "Job", location: "Rental", recrute: "Hiring", candidate: "Applying" },
      publish: { service: "Offer a service", vente: "Sell an item", demande: "Post a request", emploi: "Job offer / Search", location: "Rental" },
      modal: {
        title: "Post a service ad",
        modeProposer: "🔧 Offer",
        modeDemander: "🔍 Request",
        categoryLabel: "Category",
        categoryPlaceholder: "Search a category...",
        categoryNotFound: "No category found",
        titreProposer: "Service title",
        titreDemander: "What you're looking for",
        placeholderTitreProposer: "Ex: Plumber available in Algiers",
        placeholderTitreDemander: "Ex: Looking for an electrician",
        descLabel: "Description",
        placeholderDescProposer: "Describe your service, areas, experience...",
        placeholderDescDemander: "Describe your need in detail...",
        wilayaLabel: "Wilaya",
        wilayaPlaceholder: "Select your wilaya",
        dateLabel: "Desired date",
        dateFlexible: "Flexible date / to discuss",
        submitProposer: "Post my service",
        submitDemander: "Post my request",
        publishing: "Publishing...",
        successTitle: "Ad posted!",
        successSub: "It now appears in the feed.",
        charMin: "min",
      },
    },
  },
};

type Translations = typeof translations.fr;

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: Translations;
  dir: "ltr" | "rtl";
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "fr",
  setLang: () => {},
  t: translations.fr,
  dir: "ltr",
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>("fr");
  const dir: "ltr" | "rtl" = lang === "ar" ? "rtl" : "ltr";

  useEffect(() => {
    document.documentElement.lang = lang;
    document.documentElement.dir = dir;
  }, [lang, dir]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t: translations[lang], dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
